
-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    "fullName" TEXT,
    phone TEXT UNIQUE,
    email TEXT,
    password TEXT,
    "refCode" TEXT UNIQUE,
    "uplineRefCode" TEXT,
    role TEXT DEFAULT 'user',
    "accountType" TEXT DEFAULT 'free',
    "joiningDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "balanceFree" NUMERIC DEFAULT 0,
    "balancePremium" NUMERIC DEFAULT 0,
    "totalWithdraw" NUMERIC DEFAULT 0,
    "isBlocked" BOOLEAN DEFAULT FALSE,
    "profileImage" TEXT,
    "referralJobQuota" INTEGER DEFAULT 0
);

-- 2. Settings Table (Stores Config, Slider, Promo, Social Rates)
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value JSONB
);

-- Default Settings Insert (Only if empty)
INSERT INTO settings (value)
SELECT '{
    "appName": "Next Level Earn",
    "marqueeText": "Welcome to Next Level Earn! Withdraw is active.",
    "sliderImages": [
        "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&auto=format&fit=crop&q=60",
        "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&auto=format&fit=crop&q=60",
        "https://images.unsplash.com/photo-1628157588553-5eeea00af15c?w=800&auto=format&fit=crop&q=60",
        "https://images.unsplash.com/photo-1556742049-0cfed4f7a07d?w=800&auto=format&fit=crop&q=60"
    ],
    "promo": {
        "title": "ধামাকা অফার ২০২৬",
        "desc": "আমাদের স্পেশাল অফারটি লুফে নিন! সীমিত সময়ের জন্য।",
        "link": "https://google.com"
    },
    "socialRates": { "gmail": 10, "facebook": 5, "instagram": 5, "tiktok": 5 },
    "socialDesc": { "gmail": "", "facebook": "", "instagram": "", "tiktok": "" },
    "supportLink": "https://t.me/support",
    "groupLink": "https://t.me/group",
    "channelLink": "https://t.me/channel",
    "youtubeLink": "https://youtube.com",
    "minWithdraw": 100,
    "freeWithdrawLimit": 1,
    "bkash": "01700000000",
    "nagad": "01800000000",
    "premiumCost": 500,
    "taskEnabled": true
}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM settings);

-- 3. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "userId" TEXT REFERENCES users(id) ON DELETE CASCADE,
    type TEXT, -- deposit, withdraw, earning, purchase, bonus, transfer
    category TEXT, -- task, gmail_request, sell, typing, quiz, salary, main
    amount NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending',
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    method TEXT,
    details TEXT, 
    "senderNumber" TEXT,
    "trxId" TEXT,
    "sourceWallet" TEXT
);

-- 4. Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    "desc" TEXT,
    reward NUMERIC,
    link TEXT,
    type TEXT DEFAULT 'free',
    image TEXT
);

-- 5. Typing Jobs Table
CREATE TABLE IF NOT EXISTS typing_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT,
    reward NUMERIC,
    link TEXT,
    "waitTime" INTEGER DEFAULT 10,
    category TEXT DEFAULT 'premium'
);

-- 6. Quiz Packages Table
CREATE TABLE IF NOT EXISTS quiz_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    "desc" TEXT,
    price NUMERIC,
    duration INTEGER,
    "dailyLimit" INTEGER,
    profit NUMERIC
);

-- 7. Quiz Questions List
CREATE TABLE IF NOT EXISTS quiz_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "packageId" BIGINT REFERENCES quiz_packages(id) ON DELETE CASCADE,
    question TEXT,
    ans TEXT,
    reward NUMERIC,
    wait INTEGER,
    "adLink" TEXT
);

-- 8. Salary Plans Table
CREATE TABLE IF NOT EXISTS salary_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    "targetRefers" INTEGER,
    reward NUMERIC,
    "desc" TEXT,
    "requiredPackages" INTEGER DEFAULT 0
);

-- 9. Balance Increment Function (RPC)
-- This allows atomic updates to user balances
CREATE OR REPLACE FUNCTION increment_balance(user_id TEXT, amount NUMERIC, field TEXT)
RETURNS VOID AS $$
BEGIN
    IF field = 'balanceFree' THEN
        UPDATE users SET "balanceFree" = "balanceFree" + amount WHERE id = user_id;
    ELSIF field = 'balancePremium' THEN
        UPDATE users SET "balancePremium" = "balancePremium" + amount WHERE id = user_id;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 10. Enable Row Level Security (RLS)
-- Currently set to allow public access for simplicity. 
-- For production, you should restrict this.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE typing_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Users" ON users FOR ALL USING (true);
CREATE POLICY "Public Trx" ON transactions FOR ALL USING (true);
CREATE POLICY "Public Settings" ON settings FOR ALL USING (true);
CREATE POLICY "Public Tasks" ON tasks FOR ALL USING (true);
CREATE POLICY "Public Typing" ON typing_jobs FOR ALL USING (true);
CREATE POLICY "Public QuizPkg" ON quiz_packages FOR ALL USING (true);
CREATE POLICY "Public QuizList" ON quiz_list FOR ALL USING (true);
CREATE POLICY "Public Salary" ON salary_plans FOR ALL USING (true);
